name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push the client image
      uses: docker/build-push-action@v2
      with:
        context: client
        file: client/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubclient:latest

    - name: Build and push the server image
      uses: docker/build-push-action@v2
      with:
        context: server
        file: server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubserver:latest

    - name: Build and push the socket server image
      uses: docker/build-push-action@v2
      with:
        context: socket-server
        file: socket-server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubsocketserver:latest

    - name: Set up Google Cloud credentials
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > auth.json
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init -target=module.production

    - name: Terraform plan
      run: terraform plan -target=module.production

    - name: Terraform apply
      run: terraform apply -auto-approve -target=module.production
