name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - release

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set up Google Cloud credentials for file-gateway
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > file-gateway/auth.json

    - name: Build and push the client image
      uses: docker/build-push-action@v2
      with:
        context: client
        file: client/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubclient:${{ github.sha }}

    - name: Build and push the server image
      uses: docker/build-push-action@v2
      with:
        context: server
        file: server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubserver:${{ github.sha }}

    - name: Build and push the socket server image
      uses: docker/build-push-action@v2
      with:
        context: socket-server
        file: socket-server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubsocketserver:${{ github.sha }}
    
    - name: Build and push the file gateway image
      uses: docker/build-push-action@v2
      with:
        context: file-gateway
        file: file-gateway/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubfilegateway:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud credentials
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > auth.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/auth.json" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -input=false -force-copy

    # - name: Terraform destroy
    #   run: terraform destroy -auto-approve -target=module.production

    - name: Terraform Validate
      run: terraform validate

    - name: Set variables for Terraform
      run: |
        echo "project_id = \"${{ secrets.PROJECT_ID }}\"" >> production.auto.tfvars
        echo "socket_server_image = \"${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubsocketserver:${{ github.sha }}\"" >> production.auto.tfvars
        echo "file_gateway_image = \"${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubfilegateway:${{ github.sha }}\"" >> production.auto.tfvars
        echo "client_image = \"${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubclient:${{ github.sha }}\"" >> production.auto.tfvars
        echo "server_image = \"${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubserver:${{ github.sha }}\"" >> production.auto.tfvars
        echo "mongo_org_id = \"${{ secrets.MONGO_ORG_ID }}\"" >> production.auto.tfvars
        echo "mongo_public_key = \"${{ secrets.MONGO_PUBLIC_KEY }}\"" >> production.auto.tfvars        
        echo "mongo_private_key = \"${{ secrets.MONGO_PRIVATE_KEY }}\"" >> production.auto.tfvars
        echo "mongo_dbuser_password = \"${{ secrets.MONGO_DBUSER_PASSWORD }}\"" >> production.auto.tfvars
        echo "mongo_dbuser = \"${{ secrets.MONGO_DBUSER }}\"" >> production.auto.tfvars

    - name: Terraform Plan
      run: terraform plan -target=module.production -var-file=production.auto.tfvars

    - name: Terraform Apply MongoDB
      run: terraform apply -auto-approve -target=module.production_atlas -var-file=production.auto.tfvars

    - name: Terraform Apply Services
      run: terraform apply -auto-approve -target=module.production -var-file=production.auto.tfvars