name: Deploy Socket Server to Google Cloud Run

on:
  push:
    branches:
      - release
    paths:
      - 'socket-server/**'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push the socket server image
      uses: docker/build-push-action@v2
      with:
        context: socket-server
        file: socket-server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubsocketserver:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud credentials
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > auth.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/auth.json" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -input=false -force-copy

    - name: Terraform Validate
      run: terraform validate

    - name: Set variables for Terraform
      run: |
        echo "project_id = \"${{ secrets.PROJECT_ID }}\"" >> production.auto.tfvars
        echo "socket_server_image = \"${{ secrets.DOCKER_HUB_USERNAME }}/fileexchangehubsocketserver:latest\"" >> production.auto.tfvars

    - name: Terraform Plan
      run: |
        MAX_RETRIES=20
        RETRY_DELAY=30
        count=0
        until terraform plan -target=module.production_socket_server -var-file=production.auto.tfvars; do
          count=$((count + 1))
          if [ $count -ge $MAX_RETRIES ]; then
            echo "Failed after $MAX_RETRIES retries"
            exit 1
          fi
          echo "Retrying in $RETRY_DELAY seconds (attempt $count of $MAX_RETRIES)"
          sleep $RETRY_DELAY
        done

    - name: Terraform Apply
      run: |
        MAX_RETRIES=20
        RETRY_DELAY=30
        count=0
        until terraform apply -auto-approve -target=module.production_socket_server -var-file=production.auto.tfvars; do
          count=$((count + 1))
          if [ $count -ge $MAX_RETRIES ]; then
            echo "Failed after $MAX_RETRIES retries"
            exit 1
          fi
          echo "Retrying in $RETRY_DELAY seconds (attempt $count of $MAX_RETRIES)"
          sleep $RETRY_DELAY
        done

    - name: Extract Socket Server URI
      run: |
        SOCKET_SERVER_URI=$(terraform output socket_server_uri)
        echo "SOCKET_SERVER_URI=$SOCKET_SERVER_URI"

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
          
    - name: Store Server URI as GitHub Secret
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PERMISSIONS }}
      run: |
        echo "SOCKET_SERVER_URI=$SOCKET_SERVER_URI" # Just for debugging purposes, remove this line if you don't want to see it in the logs
        ENCRYPTED_VALUE=$(echo -n "$SOCKET_SERVER_URI" | gpg --symmetric --cipher-algo AES256 --batch --passphrase="$GITHUB_TOKEN" | base64 -w0)
        KEY_ID=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets/public-key" | jq -r '.key_id')
        
        curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/actions/secrets/SOCKET_SERVER_URI \
          -d '{"encrypted_value":"'"$ENCRYPTED_VALUE"'","key_id":"'"$KEY_ID"'"}'

  handle_failure:
    runs-on: ubuntu-latest
    needs: [docker-build-push, deploy]
    if: ${{ failure() }}
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v6
        with:
          token: ${{ secrets.GH_ISSUE_CREATOR_TOKEN }}
          script: |
            const issueTitle = "Deployment Socket Server Workflow Failed";
            let errorMessage = '';
            if (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure') {
              errorMessage = github.event.workflow_run.head_commit.message;
            }
            const issueBody = `Workflow **${process.env.GITHUB_WORKFLOW}** failed on the branch **${process.env.GITHUB_REF}**. The error message is as follows:
            \`\`\`
            ${errorMessage}
            \`\`\`
            Please fix the issue.`;
            
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });